### ISSUE TITLE
Unable to load pretrained XSUM_BertExtAbs model

### ISSUE THREAD

**Issue by XinyuFOX** [yunzhusong/AARD#2]
Hello,
  
The code raised an error during the pre-trained model checkpoint loading.
  
Here is the error code.
~~~
!python3 main.py -train_detector -train_adv -fold '0,1,2,3,4'  -dataset_dir '../dataset/Pheme' -savepath '../results/Pheme' -batch_size 48 -filter True -log_tensorboard -warmup_steps 100 

                                                                   ...
                                                                   ...
[2023-01-31 05:42:59,324 INFO] TrainData | nonR: 1488, R: 1488 (TR: 0, FR: 0, UR 0)
[2023-01-31 05:42:59,326 INFO] TestData | nonR: 372, R: 372 (TR: 0, FR: 0, UR 0)
[2023-01-31 05:42:59,499 INFO] Loading generation branch checkpoint from ../results/pretrain/XSUM_BertExtAbs/
Traceback (most recent call last):
  File "main.py", line 218, in <module>
    trainer = RumorTrainer(args, args.savepath, tokenizer, iter, fold)
  File "/home/jovyan/rumor/AARD/src/models/trainer_gen.py", line 67, in __init__
    self.model = RumorDetector(args, self.device, self.symbols, checkpoint_gen=checkpoint_gen)
  File "/home/jovyan/rumor/AARD/src/models/model.py", line 210, in __init__
    self.load_state_dict(checkpoint_gen['model'], strict=False)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1392, in load_state_dict
    load(self)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1390, in load
    load(child, prefix + name + '.')
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1390, in load
    load(child, prefix + name + '.')
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1390, in load
    load(child, prefix + name + '.')
  [Previous line repeated 1 more time]
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1386, in load
    module._load_from_state_dict(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1310, in _load_from_state_dict
    hook(state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
  File "/opt/conda/lib/python3.8/site-packages/torch_geometric/nn/dense/linear.py", line 131, in _lazy_load_hook
    weight = state_dict[prefix + 'weight']
KeyError: 'classifier.pooler.conv.lin.weight'
~~~

Any help would be appreciated, thanks :)

**Comment by yunzhusong** [comment]
Hi, XinyuFOX

Thanks for being interested in our work!

I think the **version mismatch** for the library _torch_geometric_ causes the error.
Specifically, the layer `self.lin` in _GCNConv_ is added after version _2.0.0_, while our released code runs on version _1.3.2_.
To fix the issue, you may change the running version of  _torch_geometric_ lower than _2.0.0_.

For more environment setup, please refer to the _requirements.txt_.

Thanks!

**Comment by XinyuFOX** [comment]
Thanks, Yunzhu!
